import type { Metadata } from "next";
import { Outfit } from 'next/font/google';
import './globals.css';
import { CustomerProvider } from '@/contexts/CustomerContext'; 


const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
      <body>
      <CustomerProvider> {/* ADD THIS */}
          {children}
        </CustomerProvider>
      </body>
    </html>
  );
}
